-- TABELA GERENTES --
INSERT INTO GERENTES (NOME, IDADE, APELIDO,ATIVO,DT_CONTRATO)
VALUES ('Deodoro da Fonseca',40,'Deodoro','S',to_date('20/11/2025','DD/MM/YYYY'));

INSERT INTO GERENTES (NOME, IDADE, APELIDO,ATIVO,DT_CONTRATO)
VALUES ('Floriano Peixoto',39,'Floriano','S',to_date('20/11/2025','DD/MM/YYYY'));

INSERT INTO GERENTES (NOME, IDADE, APELIDO,ATIVO,DT_CONTRATO)
VALUES ('Prudente de Moraes',38,'Prudente','S',to_date('20/11/2025','DD/MM/YYYY'));

INSERT INTO GERENTES (NOME, IDADE, APELIDO,ATIVO,DT_CONTRATO)
VALUES ('Campos Salles',37,'Campos','S',to_date('20/11/2025','DD/MM/YYYY'));

INSERT INTO GERENTES (NOME, IDADE, APELIDO,ATIVO,DT_CONTRATO)
VALUES ('Rodrigues Alves',36,'Campos','S',to_date('20/11/2025','DD/MM/YYYY'));

INSERT INTO GERENTES (NOME, IDADE, APELIDO,ATIVO,DT_CONTRATO,DT_DESLIGADO)
VALUES ('Affonso Penna',35,'Affonso','N',to_date('20/11/2025','DD/MM/YYYY'),to_date('20/11/2026','DD/MM/YYYY'));

-- TABELA ACADEMIAS -- 

INSERT INTO ACADEMIAS (CIDADE, BAIRRO, DT_INAUGURADA, IDADE, ID_GERENTE, ATIVA)
VALUES ('Bauru','Vila Pacifico',to_date('20/11/2025','DD/MM/YYYY'), 0, 1, 'S');

INSERT INTO ACADEMIAS (CIDADE, BAIRRO, DT_INAUGURADA, IDADE, ID_GERENTE, ATIVA)
VALUES ('Bauru','Centro',to_date('20/11/2025','DD/MM/YYYY'), 0, 2, 'S');

INSERT INTO ACADEMIAS (CIDADE, BAIRRO, DT_INAUGURADA, IDADE, ID_GERENTE, ATIVA)
VALUES ('Bauru','Vila Ipiranga',to_date('20/11/2025','DD/MM/YYYY'), 0, 3, 'S');

INSERT INTO ACADEMIAS (CIDADE, BAIRRO, DT_INAUGURADA, IDADE, ID_GERENTE, ATIVA)
VALUES ('Bauru','Jardim Redentor',to_date('20/11/2025','DD/MM/YYYY'), 0, 4, 'S');

INSERT INTO ACADEMIAS (CIDADE, BAIRRO, DT_INAUGURADA, IDADE, ID_GERENTE, ATIVA)
VALUES ('Bauru','Vista Alegre',to_date('20/11/2025','DD/MM/YYYY'), 0, 5, 'S');

INSERT INTO ACADEMIAS (CIDADE, BAIRRO, DT_INAUGURADA, IDADE, ID_GERENTE, ATIVA, DT_ENCERRADA)
VALUES ('Bauru','Centro',to_date('20/11/2025','DD/MM/YYYY'), 0, 6, 'N',to_date('20/11/2026','DD/MM/YYYY'));

-- TABELA OBJETIVOS --

INSERT INTO OBJETIVOS (OBJETIVO) VALUES ('Reduzir gordura corporal');
INSERT INTO OBJETIVOS (OBJETIVO) VALUES ('Ganhar massa corporal');
INSERT INTO OBJETIVOS (OBJETIVO) VALUES ('Fortalecer articulacões');  
INSERT INTO OBJETIVOS (OBJETIVO) VALUES ('Recuperação');
INSERT INTO OBJETIVOS (OBJETIVO) VALUES ('Reduzir gordura corporal');
INSERT INTO OBJETIVOS (OBJETIVO) VALUES ('Melhora cardiovascular');
INSERT INTO OBJETIVOS (OBJETIVO) VALUES ('Ganhar resistência muscular');
INSERT INTO OBJETIVOS (OBJETIVO) VALUES ('Aumentar força');
INSERT INTO OBJETIVOS (OBJETIVO) VALUES ('Ganhar mobilidade');
INSERT INTO OBJETIVOS (OBJETIVO) VALUES ('Saúde mental');

-- TABELA ALUNOS -- 

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Carla Moura Santos','12345678902','F',TO_DATE('10/03/1988','DD/MM/YYYY'),36,65,165,2);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Ricardo Alves Monteiro','12345678903','M',TO_DATE('15/07/1979','DD/MM/YYYY'),45,82,178,3);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Fernanda Lima Rocha','12345678904','F',TO_DATE('22/01/1992','DD/MM/YYYY'),33,70,170,4);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Marcos Túlio Ferreira','12345678905','M',TO_DATE('30/11/2000','DD/MM/YYYY'),24,77,180,5);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Aline Barbosa Couto','12345678906','F',TO_DATE('09/08/1985','DD/MM/YYYY'),39,60,160,6);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('José Carlos Andrade','12345678907','M',TO_DATE('05/04/1965','DD/MM/YYYY'),59,85,172,7);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Patrícia Gomes Silva','12345678908','F',TO_DATE('12/12/1999','DD/MM/YYYY'),25,72,169,8);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Diego da Costa','12345678909','M',TO_DATE('18/06/1997','DD/MM/YYYY'),27,88,182,9);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Juliana Freitas Cunha','12345678910','F',TO_DATE('04/05/1981','DD/MM/YYYY'),43,67,164,10);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Eduardo Pacheco','12345678911','M',TO_DATE('02/02/1990','DD/MM/YYYY'),34,80,179,1);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Mônica Duarte','12345678912','F',TO_DATE('07/07/1977','DD/MM/YYYY'),47,59,158,2);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Rafael Moreira','12345678913','M',TO_DATE('16/09/1983','DD/MM/YYYY'),41,91,185,3);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Bruna Carvalho','12345678914','F',TO_DATE('23/03/1994','DD/MM/YYYY'),30,62,162,4);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Felipe Antunes','12345678915','M',TO_DATE('21/11/1989','DD/MM/YYYY'),35,74,176,5);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Helena Souza','12345678916','F',TO_DATE('08/01/2002','DD/MM/YYYY'),22,58,159,6);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('André Lima','12345678917','M',TO_DATE('30/10/1970','DD/MM/YYYY'),54,86,175,7);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Daniela Fontes','12345678918','F',TO_DATE('14/06/1986','DD/MM/YYYY'),38,63,167,8);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Thiago Nunes','12345678919','M',TO_DATE('11/04/1998','DD/MM/YYYY'),26,90,183,9);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Laura Figueiredo','12345678920','F',TO_DATE('27/07/1996','DD/MM/YYYY'),28,71,168,10);


INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Alexandre Reis','12345678921','M',TO_DATE('19/12/1991','DD/MM/YYYY'),33,79,174,1);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Isabela Martins','12345678922','F',TO_DATE('05/06/1980','DD/MM/YYYY'),44,68,166,2);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Gustavo Tavares','12345678923','M',TO_DATE('02/08/1975','DD/MM/YYYY'),49,88,181,3);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Tatiane Neves','12345678924','F',TO_DATE('10/11/1993','DD/MM/YYYY'),31,57,160,4);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Bruno Santana','12345678925','M',TO_DATE('14/02/1984','DD/MM/YYYY'),40,92,188,5);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Letícia Prado','12345678926','F',TO_DATE('17/04/2004','DD/MM/YYYY'),20,55,158,6);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Fernando Nogueira','12345678927','M',TO_DATE('25/09/1968','DD/MM/YYYY'),56,83,173,7);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Denise Moraes','12345678928','F',TO_DATE('30/01/1997','DD/MM/YYYY'),27,69,171,8);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Samuel Barros','12345678929','M',TO_DATE('09/09/1990','DD/MM/YYYY'),34,87,184,9);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Renata Vasconcelos','12345678930','F',TO_DATE('03/03/1982','DD/MM/YYYY'),42,61,163,10);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Marcelo Teixeira','12345678931','M',TO_DATE('13/10/1999','DD/MM/YYYY'),25,78,177,1);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Camila Sampaio','12345678932','F',TO_DATE('18/08/1987','DD/MM/YYYY'),37,64,165,2);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Vinícius Lopes','12345678933','M',TO_DATE('07/06/2001','DD/MM/YYYY'),23,84,180,3);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Rafaela Correia','12345678934','F',TO_DATE('21/04/1978','DD/MM/YYYY'),46,73,169,4);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Pedro Henrique','12345678935','M',TO_DATE('28/01/1960','DD/MM/YYYY'),64,89,178,5);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Manuela Rios','12345678936','F',TO_DATE('31/12/2003','DD/MM/YYYY'),21,56,159,6);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Henrique Duarte','12345678937','M',TO_DATE('02/07/1974','DD/MM/YYYY'),50,82,174,7);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Viviane Costa','12345678938','F',TO_DATE('26/09/1995','DD/MM/YYYY'),29,69,168,8);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Lucas Cardoso','12345678939','M',TO_DATE('11/11/1983','DD/MM/YYYY'),41,90,183,9);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Sara Diniz','12345678940','F',TO_DATE('15/05/1990','DD/MM/YYYY'),34,72,170,10);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Alan Ribeiro','12345678941','M',TO_DATE('22/03/1981','DD/MM/YYYY'),43,88,182,1);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Natalia Portela','12345678942','F',TO_DATE('04/04/2005','DD/MM/YYYY'),19,57,160,2);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Cristiano Ramos','12345678943','M',TO_DATE('04/02/1972','DD/MM/YYYY'),52,93,186,3);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Amanda Lucena','12345678944','F',TO_DATE('29/06/1998','DD/MM/YYYY'),26,63,164,4);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Fábio Silveira','12345678945','M',TO_DATE('13/03/1986','DD/MM/YYYY'),38,76,175,5);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Bianca Andrade','12345678946','F',TO_DATE('24/12/1991','DD/MM/YYYY'),33,70,168,6);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Rodrigo Carvalho','12345678947','M',TO_DATE('20/05/1994','DD/MM/YYYY'),30,88,181,7);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Mariana de Souza','12345678948','F',TO_DATE('12/10/1982','DD/MM/YYYY'),42,66,163,8);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Thiago Marques','12345678949','M',TO_DATE('01/01/1993','DD/MM/YYYY'),31,79,176,9);

INSERT INTO ALUNOS (NOME, CPF, SEXO, DT_NASC, IDADE, PESO_KG, ALTURA_CM, ID_OBJETIVO)
VALUES ('Érica Batista','12345678950','F',TO_DATE('28/09/1997','DD/MM/YYYY'),27,60,162,10);

-- TABELA MODALIDADES -- 

INSERT INTO MODALIDADES (MODALIDADE, BONUS) VALUES ('BOXE','S');
INSERT INTO MODALIDADES (MODALIDADE, BONUS) VALUES ('CROSSFIT','N');
INSERT INTO MODALIDADES (MODALIDADE, BONUS) VALUES ('DANÇA FITNESS','N');
INSERT INTO MODALIDADES (MODALIDADE, BONUS) VALUES ('JUDÔ','N');
INSERT INTO MODALIDADES (MODALIDADE, BONUS) VALUES ('JUMP','S');
INSERT INTO MODALIDADES (MODALIDADE, BONUS) VALUES ('MUSCULAÇÃO','N');
INSERT INTO MODALIDADES (MODALIDADE, BONUS) VALUES ('MUAY THAI','N');
INSERT INTO MODALIDADES (MODALIDADE, BONUS) VALUES ('NATAÇÃO','N');
INSERT INTO MODALIDADES (MODALIDADE, BONUS) VALUES ('PILATES','S');
INSERT INTO MODALIDADES (MODALIDADE, BONUS) VALUES ('SPINNING','N');
INSERT INTO MODALIDADES (MODALIDADE, BONUS) VALUES ('YOGA','N');
INSERT INTO MODALIDADES (MODALIDADE, BONUS) VALUES ('ZUMBA','N');

-- TABELA PROFESSORES -- 

INSERT INTO PROFESSORES (NOME, APELIDO, IDADE, DT_NASC, ATIVO, DT_CONTRATO)
VALUES ('Carlos Mendes', 'Carlos', 34, TO_DATE('12/04/1990','DD/MM/YYYY'),'S', SYSDATE);

INSERT INTO PROFESSORES (NOME, APELIDO, IDADE, DT_NASC, ATIVO, DT_CONTRATO)
VALUES ('Carlos Henrique Almeida','Carlos',35,TO_DATE('12/03/1990','DD/MM/YYYY'),'S',SYSDATE);

INSERT INTO PROFESSORES (NOME, APELIDO, IDADE, DT_NASC, ATIVO, DT_CONTRATO)
VALUES ('Juliana Ramos', 'Juliana', 29, TO_DATE('20/08/1995','DD/MM/YYYY'),'S', SYSDATE);

INSERT INTO PROFESSORES (NOME, APELIDO, IDADE, DT_NASC, ATIVO, DT_CONTRATO)
VALUES ('Rafael Tavares', 'Rafael', 38, TO_DATE('05/03/1986','DD/MM/YYYY'),'S', SYSDATE);

INSERT INTO PROFESSORES (NOME, APELIDO, IDADE, DT_NASC, ATIVO, DT_CONTRATO)
VALUES ('Marina Duarte', 'Marina', 32, TO_DATE('18/11/1992','DD/MM/YYYY'),'S', SYSDATE);

INSERT INTO PROFESSORES (NOME, APELIDO, IDADE, DT_NASC, ATIVO, DT_CONTRATO)
VALUES ('Ana Carolina Silva', 'Ana', 27, TO_DATE('10/05/1997','DD/MM/YYYY'),'S', SYSDATE);

INSERT INTO PROFESSORES (NOME, APELIDO, IDADE, DT_NASC, ATIVO, DT_CONTRATO)
VALUES ('Gabriel Santos', 'Gabriel', 41, TO_DATE('14/09/1983','DD/MM/YYYY'),'S', SYSDATE);

INSERT INTO PROFESSORES (NOME, APELIDO, IDADE, DT_NASC, ATIVO, DT_CONTRATO)
VALUES ('Ricardo Hashimoto', 'Ricardo', 45, TO_DATE('22/01/1979','DD/MM/YYYY'),'S', SYSDATE);

INSERT INTO PROFESSORES (NOME, APELIDO, IDADE, DT_NASC, ATIVO, DT_CONTRATO)
VALUES ('Letícia Tanaka', 'Letícia', 30, TO_DATE('03/10/1994','DD/MM/YYYY'),'S', SYSDATE);

INSERT INTO PROFESSORES (NOME, APELIDO, IDADE, DT_NASC, ATIVO, DT_CONTRATO)
VALUES ('Vanessa Oliveira', 'Vanessa', 28, TO_DATE('15/07/1996','DD/MM/YYYY'),'S', SYSDATE);

INSERT INTO PROFESSORES (NOME, APELIDO, IDADE, DT_NASC, ATIVO, DT_CONTRATO)
VALUES ('Felipe Costa', 'Felipe', 37, TO_DATE('09/09/1987','DD/MM/YYYY'),'S', SYSDATE);

INSERT INTO PROFESSORES (NOME, APELIDO, IDADE, DT_NASC, HORARIO, ATIVO, DT_CONTRATO) 
VALUES ('Carlos Henrique Almeida', 'Carlos', 35, TO_DATE('12/03/1990','DD/MM/YYYY'), 'SEG-SEX 05:00-13:00 / SAB-DOM 05:00-10:00','S', TO_DATE('10/01/2022','DD/MM/YYYY'));

INSERT INTO PROFESSORES (NOME, APELIDO, IDADE, DT_NASC, HORARIO, ATIVO, DT_CONTRATO) 
VALUES ('Mariana Souza', 'Mariana', 29, TO_DATE('22/09/1995','DD/MM/YYYY'), 'SEG-SEX 13:00-21:00 / SAB-DOM 07:00-12:00','S', TO_DATE('15/02/2023','DD/MM/YYYY'));

INSERT INTO PROFESSORES (NOME, APELIDO, IDADE, DT_NASC, HORARIO, ATIVO, DT_CONTRATO) 
VALUES ('Rafael Santos', 'Rafael', 32, TO_DATE('05/11/1992','DD/MM/YYYY'), 'SEG-SEX 16:00-23:59 / SAB-DOM 09:00-14:00','S', TO_DATE('03/03/2021','DD/MM/YYYY'));

INSERT INTO PROFESSORES (NOME, APELIDO, IDADE, DT_NASC, HORARIO, ATIVO, DT_CONTRATO) 
VALUES ('Juliana Ribeiro', 'Juliana', 30, TO_DATE('18/07/1994','DD/MM/YYYY'), 'SEG-SEX 08:00-18:00','S', TO_DATE('12/05/2020','DD/MM/YYYY'));

INSERT INTO PROFESSORES (NOME, APELIDO, IDADE, DT_NASC, HORARIO, ATIVO, DT_CONTRATO) 
VALUES ('Fernando Oliveira', 'Fernando', 28, TO_DATE('01/02/1997','DD/MM/YYYY'), 'SEG-SEX 10:00-20:00','S', TO_DATE('09/09/2023','DD/MM/YYYY'));

INSERT INTO PROFESSORES (NOME, APELIDO, IDADE, DT_NASC, HORARIO, ATIVO, DT_CONTRATO) 
VALUES ('Bruno Martins', 'Bruno', 40, TO_DATE('30/09/1984','DD/MM/YYYY'), 'SEG-SEX 06:00-14:00 / SAB-DOM 05:00-10:00','S', TO_DATE('10/10/2021','DD/MM/YYYY'));

INSERT INTO PROFESSORES (NOME, APELIDO, IDADE, DT_NASC, HORARIO, ATIVO, DT_CONTRATO) 
VALUES ('Camila Barreto', 'Camila', 31, TO_DATE('27/04/1993','DD/MM/YYYY'), 'SEG-SEX 14:00-22:00 / SAB-DOM 07:00-12:00','S', TO_DATE('05/04/2022','DD/MM/YYYY'));

INSERT INTO PROFESSORES (NOME, APELIDO, IDADE, DT_NASC, HORARIO, ATIVO, DT_CONTRATO) 
VALUES ('Diego Freitas', 'Diego', 33, TO_DATE('25/12/1991','DD/MM/YYYY'), 'SEG-SEX 17:00-23:59 / SAB-DOM 09:00-14:00','S', TO_DATE('20/01/2020','DD/MM/YYYY'));

INSERT INTO PROFESSORES (NOME, APELIDO, IDADE, DT_NASC, HORARIO, ATIVO, DT_CONTRATO) 
VALUES ('Patrícia Lopes', 'Patrícia', 34, TO_DATE('09/08/1990','DD/MM/YYYY'), 'SEG-SEX 07:00-17:00','S', TO_DATE('11/03/2024','DD/MM/YYYY'));

INSERT INTO PROFESSORES (NOME, APELIDO, IDADE, DT_NASC, HORARIO, ATIVO, DT_CONTRATO) 
VALUES ('Thiago Moura', 'Thiago', 27, TO_DATE('20/06/1997','DD/MM/YYYY'), 'SEG-SEX 09:00-19:00','S', TO_DATE('02/02/2022','DD/MM/YYYY'));

INSERT INTO PROFESSORES (NOME, APELIDO, IDADE, DT_NASC, HORARIO, ATIVO, DT_CONTRATO) 
VALUES ('Larissa Faria', 'Larissa', 36, TO_DATE('07/10/1988','DD/MM/YYYY'), 'SEG-SEX 05:00-13:00 / SAB-DOM 07:00-12:00','S', TO_DATE('08/08/2020','DD/MM/YYYY'));

INSERT INTO PROFESSORES (NOME, APELIDO, IDADE, DT_NASC, HORARIO, ATIVO, DT_CONTRATO) 
VALUES ('Renato Ferreira', 'Renato', 42, TO_DATE('19/01/1982','DD/MM/YYYY'), 'SEG-SEX 13:00-21:00 / SAB-DOM 05:00-10:00','S', TO_DATE('19/04/2021','DD/MM/YYYY'));

INSERT INTO PROFESSORES (NOME, APELIDO, IDADE, DT_NASC, HORARIO, ATIVO, DT_CONTRATO) 
VALUES ('Sabrina Leal', 'Sabrina', 31, TO_DATE('08/12/1993','DD/MM/YYYY'), 'SEG-SEX 15:00-23:00 / SAB-DOM 09:00-14:00','S', TO_DATE('17/03/2023','DD/MM/YYYY'));

INSERT INTO PROFESSORES (NOME, APELIDO, IDADE, DT_NASC, HORARIO, ATIVO, DT_CONTRATO) 
VALUES ('Rodrigo Nascimento', 'Rodrigo', 30, TO_DATE('14/07/1994','DD/MM/YYYY'), 'SEG-SEX 06:00-16:00','S', TO_DATE('21/05/2022','DD/MM/YYYY'));

INSERT INTO PROFESSORES (NOME, APELIDO, IDADE, DT_NASC, HORARIO, ATIVO, DT_CONTRATO) 
VALUES ('Amanda Dias', 'Amanda', 26, TO_DATE('11/05/1998','DD/MM/YYYY'), 'SEG-SEX 11:00-19:00 / SAB-DOM 07:00-12:00','S', TO_DATE('13/06/2024','DD/MM/YYYY'));

INSERT INTO PROFESSORES (NOME, APELIDO, IDADE, DT_NASC, HORARIO, ATIVO, DT_CONTRATO) 
VALUES ('Gustavo Pires', 'Gustavo', 28, TO_DATE('23/03/1996','DD/MM/YYYY'), 'SEG-SEX 12:00-20:00 / SAB-DOM 05:00-10:00','S', TO_DATE('06/01/2022','DD/MM/YYYY'));

INSERT INTO PROFESSORES (NOME, APELIDO, IDADE, DT_NASC, HORARIO, ATIVO, DT_CONTRATO) 
VALUES ('Helena Vilela', 'Helena', 39, TO_DATE('29/09/1985','DD/MM/YYYY'), 'SEG-SEX 08:00-18:00','S', TO_DATE('14/09/2020','DD/MM/YYYY'));

INSERT INTO PROFESSORES (NOME, APELIDO, IDADE, DT_NASC, HORARIO, ATIVO, DT_CONTRATO) 
VALUES ('Marcelo Azevedo', 'Marcelo', 33, TO_DATE('16/02/1991','DD/MM/YYYY'), 'SEG-SEX 16:00-23:59 / SAB-DOM 07:00-12:00','S', TO_DATE('01/03/2021','DD/MM/YYYY'));

INSERT INTO PROFESSORES (NOME, APELIDO, IDADE, DT_NASC, HORARIO, ATIVO, DT_CONTRATO) 
VALUES ('Beatriz Cunha', 'Beatriz', 37, TO_DATE('10/11/1987','DD/MM/YYYY'), 'SEG-SEX 05:00-15:00','S', TO_DATE('04/11/2024','DD/MM/YYYY'));

INSERT INTO PROFESSORES (NOME, APELIDO, IDADE, DT_NASC, HORARIO, ATIVO, DT_CONTRATO) 
VALUES ('Fábio Teixeira', 'Fábio', 29, TO_DATE('18/01/1995','DD/MM/YYYY'), 'SEG-SEX 13:00-21:00 / SAB-DOM 09:00-14:00','S', TO_DATE('07/07/2023','DD/MM/YYYY'));

INSERT INTO PROFESSORES (NOME, APELIDO, IDADE, DT_NASC, HORARIO, ATIVO, DT_CONTRATO) 
VALUES ('Viviane Rocha', 'Viviane', 32, TO_DATE('03/05/1992','DD/MM/YYYY'), 'SEG-SEX 10:00-20:00 / SAB-DOM 05:00-10:00','S', TO_DATE('09/09/2021','DD/MM/YYYY'));

INSERT INTO PROFESSORES (NOME, APELIDO, IDADE, DT_NASC, HORARIO, ATIVO, DT_CONTRATO) 
VALUES ('Leonardo Prado', 'Leonardo', 34, TO_DATE('02/02/1990','DD/MM/YYYY'), 'SEG-SEX 07:00-17:00','S', TO_DATE('12/12/2022','DD/MM/YYYY'));


-- TABELA PLANOS -- 

INSERT INTO PLANOS (PLANO, DURACAO_MES, VALOR_R$,VALOR_MES_R$) VALUES ('Mensal',1,100,100);
INSERT INTO PLANOS (PLANO, DURACAO_MES, VALOR_R$,VALOR_MES_R$) VALUES ('Bimestral',2,180,90);
INSERT INTO PLANOS (PLANO, DURACAO_MES, VALOR_R$,VALOR_MES_R$) VALUES ('Trimestral',3,240,80);
INSERT INTO PLANOS (PLANO, DURACAO_MES, VALOR_R$,VALOR_MES_R$) VALUES ('Semestral',6,420,70);
INSERT INTO PLANOS (PLANO, DURACAO_MES, VALOR_R$,VALOR_MES_R$) VALUES ('Novemestral',9,540,60);
INSERT INTO PLANOS (PLANO, DURACAO_MES, VALOR_R$,VALOR_MES_R$) VALUES ('Anual',12,600,50);


-- TABELA HORARIOS -- 

INSERT INTO HORARIOS (DIA_SEMANA, HORA_INICIO, HORA_FINAL) VALUES ('SEG',8,9);
INSERT INTO HORARIOS (DIA_SEMANA, HORA_INICIO, HORA_FINAL) VALUES ('SEG',14,15);
INSERT INTO HORARIOS (DIA_SEMANA, HORA_INICIO, HORA_FINAL) VALUES ('SEG',17,18);
INSERT INTO HORARIOS (DIA_SEMANA, HORA_INICIO, HORA_FINAL) VALUES ('SEG',19,20);
INSERT INTO HORARIOS (DIA_SEMANA, HORA_INICIO, HORA_FINAL) VALUES ('SEG',20,21);
INSERT INTO HORARIOS (DIA_SEMANA, HORA_INICIO, HORA_FINAL) VALUES ('TER',5,24);
INSERT INTO HORARIOS (DIA_SEMANA, HORA_INICIO, HORA_FINAL) VALUES ('TER',6,7);
INSERT INTO HORARIOS (DIA_SEMANA, HORA_INICIO, HORA_FINAL) VALUES ('TER',8,9);
INSERT INTO HORARIOS (DIA_SEMANA, HORA_INICIO, HORA_FINAL) VALUES ('TER',18,19);
INSERT INTO HORARIOS (DIA_SEMANA, HORA_INICIO, HORA_FINAL) VALUES ('TER',20,21);
INSERT INTO HORARIOS (DIA_SEMANA, HORA_INICIO, HORA_FINAL) VALUES ('QUA',5,24);
INSERT INTO HORARIOS (DIA_SEMANA, HORA_INICIO, HORA_FINAL) VALUES ('QUA',8,9);
INSERT INTO HORARIOS (DIA_SEMANA, HORA_INICIO, HORA_FINAL) VALUES ('QUA',14,15);
INSERT INTO HORARIOS (DIA_SEMANA, HORA_INICIO, HORA_FINAL) VALUES ('QUA',17,18);
INSERT INTO HORARIOS (DIA_SEMANA, HORA_INICIO, HORA_FINAL) VALUES ('QUA',19,20);
INSERT INTO HORARIOS (DIA_SEMANA, HORA_INICIO, HORA_FINAL) VALUES ('QUA',20,21);
INSERT INTO HORARIOS (DIA_SEMANA, HORA_INICIO, HORA_FINAL) VALUES ('QUI',5,24);
INSERT INTO HORARIOS (DIA_SEMANA, HORA_INICIO, HORA_FINAL) VALUES ('QUI',6,7);
INSERT INTO HORARIOS (DIA_SEMANA, HORA_INICIO, HORA_FINAL) VALUES ('QUI',8,9);
INSERT INTO HORARIOS (DIA_SEMANA, HORA_INICIO, HORA_FINAL) VALUES ('QUI',18,19);
INSERT INTO HORARIOS (DIA_SEMANA, HORA_INICIO, HORA_FINAL) VALUES ('QUI',20,21);
INSERT INTO HORARIOS (DIA_SEMANA, HORA_INICIO, HORA_FINAL) VALUES ('SEX',5,24);
INSERT INTO HORARIOS (DIA_SEMANA, HORA_INICIO, HORA_FINAL) VALUES ('SEX',8,9);
INSERT INTO HORARIOS (DIA_SEMANA, HORA_INICIO, HORA_FINAL) VALUES ('SEX',14,15);
INSERT INTO HORARIOS (DIA_SEMANA, HORA_INICIO, HORA_FINAL) VALUES ('SEX',17,18);
INSERT INTO HORARIOS (DIA_SEMANA, HORA_INICIO, HORA_FINAL) VALUES ('SEX',19,20);
INSERT INTO HORARIOS (DIA_SEMANA, HORA_INICIO, HORA_FINAL) VALUES ('SEX',20,21);
INSERT INTO HORARIOS (DIA_SEMANA, HORA_INICIO, HORA_FINAL) VALUES ('SAB',5,14);
INSERT INTO HORARIOS (DIA_SEMANA, HORA_INICIO, HORA_FINAL) VALUES ('SAB',7,8);
INSERT INTO HORARIOS (DIA_SEMANA, HORA_INICIO, HORA_FINAL) VALUES ('SAB',8,9);
INSERT INTO HORARIOS (DIA_SEMANA, HORA_INICIO, HORA_FINAL) VALUES ('DOM',5,14);
INSERT INTO HORARIOS (DIA_SEMANA, HORA_INICIO, HORA_FINAL) VALUES ('DOM',7,8);
INSERT INTO HORARIOS (DIA_SEMANA, HORA_INICIO, HORA_FINAL) VALUES ('DOM',8,9);


-- TABELA ACAD_HORA_PROF_MUSC -- 

INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1, 1, 12, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1, 8, 12, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1, 13, 12, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1, 19, 12, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1, 24, 12, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1, 30, 12, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1, 33, 12, 6);

INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1, 1, 13, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1, 8, 13, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1, 13, 13, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1, 19, 13, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1, 24, 13, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1, 30, 13, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1, 33, 13, 6);

INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1, 1, 14, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1, 8, 14, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1, 13, 14, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1, 19, 142, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1, 24, 14, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1, 30, 14, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1, 33, 14, 6);

INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1, 1, 15, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1, 8, 15, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1, 13, 15, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1, 19, 15, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1, 24, 15, 6);

INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1, 1, 16, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1, 8, 16, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1, 13, 16, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1, 19, 16, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1, 24, 16, 6);

INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2, 1, 17, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2, 8, 17, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2, 13, 17, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2, 19, 17, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2, 24, 17, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2, 30, 17, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2, 33, 17, 6);

INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2, 1, 18, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2, 8, 18, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2, 13, 18, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2, 19, 18, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2, 24, 18, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2, 30, 18, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2, 33, 18, 6);

INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2, 1, 19, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2, 8, 19, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2, 13, 19, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2, 19, 19, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2, 24, 19, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2, 30, 19, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2, 33, 19, 6);

INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2, 1, 20, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2, 8, 20, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2, 13, 20, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2, 19, 20, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2, 24, 20, 6);

INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3, 1, 21, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3, 8, 21, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3, 13, 21, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3, 19, 21, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3, 24, 21, 6);

INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3, 1, 22, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3, 8, 22, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3, 13, 22, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3, 19, 22, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3, 24, 22, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3, 30, 22, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3, 33, 22, 6);

INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3, 1, 23, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3, 8, 23, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3, 13, 23, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3, 19, 23, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3, 24, 23, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3 ,30, 23, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3, 33, 23, 6);

INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3, 1, 24, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3, 8, 24, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3, 13, 24, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3, 19, 24, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3, 24, 24, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3, 30, 24, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3, 33, 24, 6);

INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4, 1, 25, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4, 8, 25, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4, 13, 25, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4, 19, 25, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4, 24, 25, 6);

INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4, 1, 26, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4, 8, 26, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4, 13, 26, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4, 19, 26, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4, 24, 26, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4, 30, 26, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4, 33, 26, 6);

INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4, 1, 27, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4, 8, 27, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4, 13, 27, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4, 19, 27, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4, 24, 27, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4, 30, 27, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4, 33, 27, 6);

INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4, 1, 28, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4, 8, 28, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4, 13, 28, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4, 19, 28, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4, 24, 28, 6);

INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4, 1, 29, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4, 8, 29, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4, 13, 29, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4, 19, 29, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4, 24, 29, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4, 30, 29, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4, 33, 29, 6);

INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5, 1, 30, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5, 8, 30, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5, 13, 30, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5, 19, 30, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5, 24, 30, 6);

INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5, 1, 31, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5, 8, 31, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5, 13, 31, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5, 19, 31, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5, 24, 31, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5, 30, 31, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5, 33, 31, 6);

INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5, 1, 32, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5, 8, 32, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5, 13, 32, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5, 19, 32, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5, 24, 32, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5, 30, 32, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5, 33, 32, 6);

INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5, 1, 33, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5, 8, 33, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5, 13, 33, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5, 19, 33, 6);
INSERT INTO ACAD_HORA_PROF_MUSC (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5, 24, 33, 6);

-- TABELA ACAD_HORA_PROF_MOD -- 

INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1,2,1,1);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1,5,1,1);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1,15,1,1);

INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1,3,3,3);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1,6,3,3);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1,16,3,3);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1,29,3,3);

INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1,4,5,5);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1,7,5,5);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1,17,5,5);

INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1,5,8,8);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1,9,8,8);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1,18,8,8);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1,31,8,8);

INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1,6,11,11);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1,10,11,11);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1,20,11,11);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (1,32,11,11);

INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2,2,2,2);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2,11,2,2);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2,22,2,2);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2,32,2,2);

INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2,4,3,3);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2,12,3,3);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2,23,3,3);

INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2,2,4,4);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2,16,4,4);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2,32,4,4);

INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2,3,7,7);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2,14,7,7);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2,25,7,7);

INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2,4,10,10);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2,20,10,10);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2,31,10,10);

INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2,2,12,12);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2,12,12,12);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2,17,12,12);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (2,32,12,12);

INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3,4,1,1);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3,18,1,1);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3,29,1,1);

INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3,6,5,5);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3,15,5,5);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3,25,5,5);

INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3,4,7,7);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3,16,7,7);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3,32,7,7);

INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3,6,8,8);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3,17,8,8);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3,29,8,8);

INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3,2,9,9);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3,11,9,9);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3,21,9,9);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3,31,9,9);

INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3,3,12,12);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3,15,12,12);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (3,31,12,12);

INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4,3,2,2);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4,10,2,2);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4,21,2,2);

INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4,7,3,3);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4,14,3,3);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4,25,3,3);

INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4,3,4,4);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4,7,4,4);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4,14,4,4);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4,31,4,4);

INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4,3,8,8);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4,20,8,8);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4,26,8,8);

INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4,2,10,10);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4,11,10,10);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4,18,10,10);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4,29,10,10);

INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4,4,12,12);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4,14,12,12);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (4,27,12,12);

INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5,4,2,2);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5,14,2,2);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5,23,2,2);

INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5,5,3,3);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5,9,3,3);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5,15,3,3);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5,18,3,3);

INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5,4,8,8);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5,15,8,8);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5,25,8,8);

INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5,4,9,9);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5,17,9,9);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5,29,9,9);

INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5,4,11,11);
INSERT INTO ACAD_HORA_PROF_MOD (ID_ACAD, ID_HORARIO, ID_PROF, ID_MODALIDADE) VALUES (5,25,11,11);


-- TABELA METAS -- 

INSERT INTO METAS (META,ID_ALUNO) VALUES ('Correr 4km em 15 minutos',1);
INSERT INTO METAS (META,ID_ALUNO) VALUES ('Correr 10km em 35 minutos',2);
INSERT INTO METAS (META,ID_ALUNO) VALUES ('Levantar 120kg no supino reto',3);
INSERT INTO METAS (META,ID_ALUNO) VALUES ('Levantamento terra com 200kg',4);
INSERT INTO METAS (META,ID_ALUNO) VALUES ('Agachamento livre com 100kg',5);
INSERT INTO METAS (META,ID_ALUNO) VALUES ('Alcançar 10% de BF',6);
INSERT INTO METAS (META,ID_ALUNO) VALUES ('Pedalar por 1 hora',7);

-- TABELA MATRICULAS -- 

INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',1,6,1);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',2,1,3);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',3,2,1);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'N',4,3,2);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',5,4,6);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',6,5,4);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'N',7,7,2);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',8,8,1);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',9,9,3);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'N',10,10,5);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',11,11,4);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',1,5,1);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',2,6,1);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',3,9,1);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',1,7,3);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',2,2,5);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',3,6,1);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',4,1,4);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',5,12,2);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',6,8,6);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',7,3,1);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',8,11,5);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',9,4,2);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',10,5,3);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',11,10,6);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',12,9,1);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',13,2,4);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',14,6,5);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',15,7,2);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',16,1,1);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',17,12,3);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',18,3,6);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',19,5,4);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',20,8,2);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',21,9,1);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',22,4,5);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',23,11,3);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',24,2,6);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',25,6,2);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',26,7,5);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',27,1,3);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',28,12,6);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',29,3,2);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',30,5,1);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',31,8,4);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',32,9,3);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',33,4,6);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',34,11,1);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',35,2,5);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',36,6,2);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',37,7,6);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',38,1,4);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',39,12,3);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',40,3,5);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',41,5,2);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',42,8,1);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',43,9,6);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',44,4,2);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',45,11,5);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',46,2,1);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',47,6,4);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',48,7,3);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',49,1,2);
INSERT INTO MATRICULAS (DT_MATRICULA, STATUS, ID_ALUNO, ID_MODALIDADE, ID_PLANO) VALUES (SYSDATE,'S',50,12,6);

-- TABELA CHECKINS_CONSECUTIVOS_PONTOS --

INSERT INTO CHECKINS_CONSECUTIVOS_PONTOS (DIAS_CONSECUTIVOS, PONTOS_ADD) VALUES (2,10);
INSERT INTO CHECKINS_CONSECUTIVOS_PONTOS (DIAS_CONSECUTIVOS, PONTOS_ADD) VALUES (5,20);
INSERT INTO CHECKINS_CONSECUTIVOS_PONTOS (DIAS_CONSECUTIVOS, PONTOS_ADD) VALUES (14,40);
INSERT INTO CHECKINS_CONSECUTIVOS_PONTOS (DIAS_CONSECUTIVOS, PONTOS_ADD) VALUES (22,80);
INSERT INTO CHECKINS_CONSECUTIVOS_PONTOS (DIAS_CONSECUTIVOS, PONTOS_ADD) VALUES (30,100);
INSERT INTO CHECKINS_CONSECUTIVOS_PONTOS (DIAS_CONSECUTIVOS, PONTOS_ADD) VALUES (45,120);
INSERT INTO CHECKINS_CONSECUTIVOS_PONTOS (DIAS_CONSECUTIVOS, PONTOS_ADD) VALUES (60,140);
INSERT INTO CHECKINS_CONSECUTIVOS_PONTOS (DIAS_CONSECUTIVOS, PONTOS_ADD) VALUES (75,160);
INSERT INTO CHECKINS_CONSECUTIVOS_PONTOS (DIAS_CONSECUTIVOS, PONTOS_ADD) VALUES (90,180);
INSERT INTO CHECKINS_CONSECUTIVOS_PONTOS (DIAS_CONSECUTIVOS, PONTOS_ADD) VALUES (100,200);
INSERT INTO CHECKINS_CONSECUTIVOS_PONTOS (DIAS_CONSECUTIVOS, PONTOS_ADD) VALUES (120,220);
INSERT INTO CHECKINS_CONSECUTIVOS_PONTOS (DIAS_CONSECUTIVOS, PONTOS_ADD) VALUES (150,240);
INSERT INTO CHECKINS_CONSECUTIVOS_PONTOS (DIAS_CONSECUTIVOS, PONTOS_ADD) VALUES (200,260);
INSERT INTO CHECKINS_CONSECUTIVOS_PONTOS (DIAS_CONSECUTIVOS, PONTOS_ADD) VALUES (220,300);
INSERT INTO CHECKINS_CONSECUTIVOS_PONTOS (DIAS_CONSECUTIVOS, PONTOS_ADD) VALUES (250,350);
INSERT INTO CHECKINS_CONSECUTIVOS_PONTOS (DIAS_CONSECUTIVOS, PONTOS_ADD) VALUES (280,400);
INSERT INTO CHECKINS_CONSECUTIVOS_PONTOS (DIAS_CONSECUTIVOS, PONTOS_ADD) VALUES (300,450);
INSERT INTO CHECKINS_CONSECUTIVOS_PONTOS (DIAS_CONSECUTIVOS, PONTOS_ADD) VALUES (320,500);
INSERT INTO CHECKINS_CONSECUTIVOS_PONTOS (DIAS_CONSECUTIVOS, PONTOS_ADD) VALUES (340,550);
INSERT INTO CHECKINS_CONSECUTIVOS_PONTOS (DIAS_CONSECUTIVOS, PONTOS_ADD) VALUES (360,600);
INSERT INTO CHECKINS_CONSECUTIVOS_PONTOS (DIAS_CONSECUTIVOS, PONTOS_ADD) VALUES (365,700);

-- TABELA DESAFIOS_TIPOS -- 

INSERT INTO DESAFIOS_TIPOS (TIPO_DESC, REINICIA, MENSAL) VALUES ('CHECKIN NO MESMO MES','S','S');
INSERT INTO DESAFIOS_TIPOS (TIPO_DESC, REINICIA, MENSAL) VALUES ('CHECKIN QUANTIDADE TOTAL','N','N');
INSERT INTO DESAFIOS_TIPOS (TIPO_DESC, REINICIA, MENSAL) VALUES ('MATRICULA REALIZADAS','N','N');
INSERT INTO DESAFIOS_TIPOS (TIPO_DESC, REINICIA, MENSAL) VALUES ('MATRICULA RENOVADAS','N','N');
INSERT INTO DESAFIOS_TIPOS (TIPO_DESC, REINICIA, MENSAL) VALUES ('TREINO MESMA MODALIDADE','N','N');
INSERT INTO DESAFIOS_TIPOS (TIPO_DESC, REINICIA, MENSAL) VALUES ('TREINO QUALQUER MODALIDADE','N','N');
INSERT INTO DESAFIOS_TIPOS (TIPO_DESC, REINICIA, MENSAL) VALUES ('TREINO MODALIDADE BONUS','S','S');
INSERT INTO DESAFIOS_TIPOS (TIPO_DESC, REINICIA, MENSAL) VALUES ('PAGAMENTOS QUANTIDADE','N','N');

-- TABELA DESAFIOS -- 

INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Fazer 15 checkins',1,15,15);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Fazer 30 checkins',1,30,40);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Fazer 45 checkins',1,45,80);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Fazer 60 checkins',1,60,100);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Fazer 75 checkins',1,75,150);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Fazer 90 checkins',1,90,250);

INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Fazer 15 checkins',2,15,10);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Fazer 30 checkins',2,30,20);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Fazer 50 checkins',2,50,40);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Fazer 100 checkins',2,100,120);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Fazer 200 checkins',2,200,250);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Fazer 500 checkins',2,500,500);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Fazer 800 checkins',2,800,1000);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Fazer 1000 checkins',2,1000,1500);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Fazer 1001+ checkins',2,1001,20);

INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Fazer 1 matricula',3,1,100);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Fazer 2 matriculas',3,21,250);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Fazer 3 matriculas',3,3,450);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Fazer 4 matriculas',3,4,600);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Fazer 5 matriculas',3,5,800);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Fazer 6+ matriculas',3,6,1000);

INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Renovar 1 matricula',4,1,100);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Renovar 2 matriculas',4,2,200);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Renovar 3 matriculas',4,31,300);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Renovar 4+ matriculas',4,4,500);

INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Registrar 10 treinos',5,10,30);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Registrar 20 treinos',5,20,80);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Registrar 40 treinos',5,40,120);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Registrar 80 treinos',5,80,200);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Registrar 100 treinos',5,100,350);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Registrar 150 treinos',5,150,550);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Registrar 300 treinos',5,300,800);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Registrar 500 treinos',5,500,1000);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Registrar 1000 treinos',5,1000,2000);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Registrar 1001+ treinos',5,1001,30);

INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Registrar 10 treinos',6,10,15);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Registrar 20 treinos',6,20,40);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Registrar 40 treinos',6,40,60);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Registrar 80 treinos',6,80,100);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Registrar 100 treinos',6,100,200);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Registrar 150 treinos',6,150,300);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Registrar 300 treinos',6,300,500);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Registrar 500 treinos',6,500,700);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Registrar 1000 treinos',6,1000,1200);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Registrar 1001+ treinos',6,1001,20);

INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Registrar 10 treinos',7,10,30);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Registrar 20 treinos',7,200,60);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Registrar 30 treinos',7,30,100);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Registrar 40 treinos',7,40,150);

INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Realizar 1 pagamento',8,1,10);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Realizar 3 pagamentos',8,3,40);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Realizar 6 pagamentos',8,6,70);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Realizar 12 pagamentos',8,12,150);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Realizar 24 pagamentos',8,24,500);
INSERT INTO DESAFIOS (DESAFIO_DESC, ID_TIPO, QTD_REQUER, PONTOS) VALUES('Realizar 25+ pagamentos',8,25,30);

-- TABELA PAGAMENTOS -- 

INSERT INTO PAGAMENTOS (DT_PAGAMENTO, FORMA_PAG, ID_MATRICULA) VALUES (SYSDATE, 'PIX', 1);
INSERT INTO PAGAMENTOS (DT_PAGAMENTO, FORMA_PAG, ID_MATRICULA) VALUES (SYSDATE, 'PIX', 5);
INSERT INTO PAGAMENTOS (DT_PAGAMENTO, FORMA_PAG, ID_MATRICULA) VALUES (SYSDATE, 'PIX', 22);
INSERT INTO PAGAMENTOS (DT_PAGAMENTO, FORMA_PAG, ID_MATRICULA) VALUES (SYSDATE, 'PIX', 14);
INSERT INTO PAGAMENTOS (DT_PAGAMENTO, FORMA_PAG, ID_MATRICULA) VALUES (SYSDATE, 'PIX', 44);
INSERT INTO PAGAMENTOS (DT_PAGAMENTO, FORMA_PAG, ID_MATRICULA) VALUES (SYSDATE, 'PIX', 32);
INSERT INTO PAGAMENTOS (DT_PAGAMENTO, FORMA_PAG, ID_MATRICULA) VALUES (SYSDATE, 'PIX', 11);
INSERT INTO PAGAMENTOS (DT_PAGAMENTO, FORMA_PAG, ID_MATRICULA) VALUES (SYSDATE, 'PIX', 4);
INSERT INTO PAGAMENTOS (DT_PAGAMENTO, FORMA_PAG, ID_MATRICULA) VALUES (SYSDATE, 'PIX', 44);
INSERT INTO PAGAMENTOS (DT_PAGAMENTO, FORMA_PAG, ID_MATRICULA) VALUES (SYSDATE, 'PIX', 60);
INSERT INTO PAGAMENTOS (DT_PAGAMENTO, FORMA_PAG, ID_MATRICULA) VALUES (SYSDATE, 'PIX', 40);
INSERT INTO PAGAMENTOS (DT_PAGAMENTO, FORMA_PAG, ID_MATRICULA) VALUES (SYSDATE, 'PIX', 22);
INSERT INTO PAGAMENTOS (DT_PAGAMENTO, FORMA_PAG, ID_MATRICULA) VALUES (SYSDATE, 'PIX', 29);
INSERT INTO PAGAMENTOS (DT_PAGAMENTO, FORMA_PAG, ID_MATRICULA) VALUES (SYSDATE, 'PIX', 37);
INSERT INTO PAGAMENTOS (DT_PAGAMENTO, FORMA_PAG, ID_MATRICULA) VALUES (SYSDATE, 'PIX', 2);

-- TABELA RECOMPENSAS -- 

INSERT INTO RECOMPENSAS (RECOMPENSA, CUSTA_PONTOS) VALUES ('Coqueleteira',150);
INSERT INTO RECOMPENSAS (RECOMPENSA, CUSTA_PONTOS) VALUES ('Garrafa de Água Personalizada',100);
INSERT INTO RECOMPENSAS (RECOMPENSA, CUSTA_PONTOS) VALUES ('Toalha de Academia',100);
INSERT INTO RECOMPENSAS (RECOMPENSA, CUSTA_PONTOS) VALUES ('Sacochila Esportiva',200);
INSERT INTO RECOMPENSAS (RECOMPENSA, CUSTA_PONTOS) VALUES ('Kit Bandas de Resistência',300);
INSERT INTO RECOMPENSAS (RECOMPENSA, CUSTA_PONTOS) VALUES ('Camiseta Dry Fit AlphaCo',400);
INSERT INTO RECOMPENSAS (RECOMPENSA, CUSTA_PONTOS) VALUES ('Fone de Ouvido Bluetooth JBL',1000);
INSERT INTO RECOMPENSAS (RECOMPENSA, CUSTA_PONTOS) VALUES ('Kit Massageador',550);
INSERT INTO RECOMPENSAS (RECOMPENSA, CUSTA_PONTOS) VALUES ('Cinturão Growth All Black',800);
INSERT INTO RECOMPENSAS (RECOMPENSA, CUSTA_PONTOS) VALUES ('Tapete de Yoga',250);
INSERT INTO RECOMPENSAS (RECOMPENSA, CUSTA_PONTOS) VALUES ('Fita Strap Growth',300);
INSERT INTO RECOMPENSAS (RECOMPENSA, CUSTA_PONTOS) VALUES ('Creatina Growth',500);
INSERT INTO RECOMPENSAS (RECOMPENSA, CUSTA_PONTOS) VALUES ('Creapure Growth',1000);
INSERT INTO RECOMPENSAS (RECOMPENSA, CUSTA_PONTOS) VALUES ('Whey Medium Growth',600);
INSERT INTO RECOMPENSAS (RECOMPENSA, CUSTA_PONTOS) VALUES ('Whey 80% Growth',1000);
INSERT INTO RECOMPENSAS (RECOMPENSA, CUSTA_PONTOS) VALUES ('Voucher 50 R$ Growth',400);
INSERT INTO RECOMPENSAS (RECOMPENSA, CUSTA_PONTOS) VALUES ('Voucher 100 R$ Growth',800);
INSERT INTO RECOMPENSAS (RECOMPENSA, CUSTA_PONTOS) VALUES ('Voucher 200 R$ Growth',1500);